config/routes.rb
Rails.application.routes.draw do
  resources :documents, except: [:edit, :update, :destroy] do
    
    collection do
      get :search
    end

  end
  get 'home/index'
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users

  root to: "home#index"
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/admin_user.rb
class AdminUser < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/document.rb
class Document < ApplicationRecord
  belongs_to :user
  has_one_attached :file

  validates :title, presence: true
  validates :file, presence: true
  validates :user_id, presence: true

  validate :correct_document_mime_type

  private

  def correct_document_mime_type
    if file.attached? && !file.content_type.in?(%w(application/zip application/pdf))
      errors.add(:file, 'Must be a PDF or a ZIP file')
    end
    if file.attached? && file.blob.byte_size > 5.megabytes
      errors.add(:file, 'Must be less than 5MB in size')
    end
  end
end

app/models/role.rb
class Role < ApplicationRecord
    has_many :users
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable,
         :confirmable, :lockable, :timeoutable, :trackable
  
  belongs_to :role
  has_many :documents
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    protect_from_forgery with: :exception

    before_action :configure_permitted_parameters, if: :devise_controller?

    protected

        def configure_permitted_parameters
            devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :roll_no, :college, :role_id, :email, :password) }
            devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password) }
        end
end

app/controllers/documents_controller.rb
class DocumentsController < ApplicationController
  before_action :set_document, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /documents or /documents.json
  def index
    @documents = Document.where(user_id: current_user.id).order("id DESC")
  end

  # GET /documents/1 or /documents/1.json
  def show
  end

  # GET /documents/new
  def new
    @document = Document.new
  end

  # GET /documents/1/edit
  def edit
  end

  # POST /documents or /documents.json
  def create
    @document = Document.new(document_params)

    respond_to do |format|
      if @document.save
        format.html { redirect_to documents_path, notice: "Document was successfully created." }
        format.json { render :show, status: :created, location: @document }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /documents/1 or /documents/1.json
  def update
    respond_to do |format|
      if @document.update(document_params)
        format.html { redirect_to documents_path, notice: "Document was successfully updated." }
        format.json { render :show, status: :ok, location: @document }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @document.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /documents/1 or /documents/1.json
  def destroy
    @document.destroy

    respond_to do |format|
      format.html { redirect_to documents_url, notice: "Document was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def search
    @documents = Document.where("title LIKE ?", "%#{params[:title]}%").order("id DESC")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_document
      @document = Document.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def document_params
      params.require(:document).permit(:title, :content, :likes, :user_id, :file)
    end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/documents_helper.rb
module DocumentsHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/documents/_form.html.erb
<%= form_with(model: document) do |form| %>
  <% if document.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(document.errors.count, "error") %> prohibited this document from being saved:</h2>

      <ul>
        <% document.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field mb-4">
    <%= form.label :title, class: 'form-field' %>
    <%= form.text_field :title, class: 'form-control' %>
  </div>

  <div class="field mb-4">
    <%= form.label :content, class: 'form-field' %>
    <%= form.text_area :content, class: 'form-control' %>
  </div>

  <div class="field mb-4">
    <%= form.label :file, class: 'form-field' %>
    <%= form.file_field :file, direct_upload: true, accept: 'application/pdf, application/zip', class: 'form-control' %>
  </div>
  
  <div class="field d-none">
    <%= form.label :user_id %>
    <%= form.number_field :user_id, :value => current_user.id %>
  </div>

  <div class="actions">
    <%= form.submit 'Upload Document', class: 'btn btn-success' %>
  </div>
<% end %>

app/views/documents/_search_form.html.erb
<div class="card">
  <h2 class="card-header">
    Document Search
  </h2>
  <div class="card-body">
     <%= form_with url: search_documents_path, local: true, method: :get do  |f| %>
        <%= text_field_tag :title, params[:title], :placeholder => "Enter Document Title", class: "form-control me-2" %>
        <div class="actions mt-2">
            <%= f.submit "Search", class: "btn btn-success" %>
        </div>
    <% end %>
  </div>
</div>

app/views/documents/edit.html.erb
<h1>Editing Document</h1>

<%= render 'form', document: @document %>

<%= link_to 'Show', @document %> |
<%= link_to 'Back', documents_path %>

app/views/documents/index.html.erb
<%= link_to 'Upload New Document', new_document_path, class: 'btn btn-primary' %>


<div class="card mt-3">
  <h5 class="card-header">Your Documents</h5>
  <div class="card-body">
    <table class="table">
      <thead>
        <tr>
          <th scope="col">Title</th>
          <th scope="col">Content</th>
          <th colspan="3"></th>
        </tr>
      </thead>

      <tbody>
        <% @documents.each do |document| %>
          <tr>
            <td><%= document.title %></td>
            <td><%= document.content %></td>
            <td><%= link_to 'View', document, class: 'btn btn-sm btn-info' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>

  </div>
</div>

app/views/documents/new.html.erb
<div class="card">
  <h5 class="card-header">New Document</h5>
  
  <div class="card-body">
    <%= render 'form', document: @document %>
  </div>
</div>

<%= link_to 'Back', documents_path, class: 'btn btn-secondary mt-4' %>

app/views/documents/search.html.erb
<% if @documents.any? %>
  <div class="row">

    <% @documents.each do |document| %>

        <div class="card" style="width: 100%;">
        <div class="card-body">

        <div class="row">

          <div class="col-4">
          <img src="https://www.iconpacks.net/icons/2/free-pdf-download-icon-2617-thumb.png" class="card-img-top" alt="pdf image png">

          </div>
          <div class="col">
          <h5 class="card-title"><%= "#{document.title} - #{document.user.name} #{document.user.role.name} (#{document.user.college})" %></h5>
          <p><%= document.content %></p>
          <br>
          <%= link_to 'Preview', document.file, preview: '', class: 'btn btn-primary' %>
          <%= link_to 'Download', document.file, Dowload: '', class: 'btn btn-success' %> 
          </div>
          
          </div>
           
          </div>
        </div>

  <% end %>
  </div>
<% end %>

app/views/documents/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @document.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @document.content %>
</p>

<p>
  <strong>Likes:</strong>
  <%= @document.likes %>
</p>

<p>
  <strong>User:</strong>
  <%= @document.user.name %>
</p>

<%= link_to "Download file", @document.file, download: '' %>
<%= link_to "Preview file", @document.file, preview: '' %>

<%= link_to 'Back', documents_path %>

app/views/home/index.html.erb
<div class="container text-center">
    <div class="row">
        <div class="col">
            <div class="card">
                <div class="card-body">
                  <h5 class="card-title">BIBLIOS is a virtual library for all your need you will get all the documents you need over here.</h5>
                    <% if user_signed_in? %>
                        <p class="card-text">You are logged in as <%= current_user.email %></p>
                    <% else %>
                        <p class="card-text">Sign in / Sign up to get the service</p>
                    <% end %>
                </div>
              </div>
        </div>
    </div>
</div>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg bg-body-tertiary">
  <div class="container-fluid">
    <%= link_to "Biblios", root_path, class: "navbar-brand" %>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0 w-100 justify-content-center">
        <li class="nav-item">
          <%= link_to "Home", root_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Documents", documents_path, class: "nav-link" %>
        </li>
        <% if user_signed_in? %>
          <ul class="navbar-nav">
            <li class="nav-item dropdown">
              <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Profile
              </a>
              <ul class="dropdown-menu">
              <li><a class="dropdown-item" href="#"><%= current_user.name %></a></li>
              <li><a class="dropdown-item" href="#"><%= current_user.email %></a></li>
              <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
              </ul>
            </li>
          </ul>
          <li class="nav-item">
            <%= link_to "Sign out", destroy_user_session_path, method: :delete, class: "nav-link" %>
          </li>

          <%= form_with url: search_documents_path, local: true, method: :get, class: 'd-flex' do  |f| %>
            <%= text_field_tag :title, params[:title], :placeholder => "Enter Document Title", class: "form-control me-2" %>
            <div class="actions m-1">
                <%= f.submit "Search", class: "btn btn-sm btn-success" %>
            </div>
          <% end %>
        
        <% else %>
          <li class="nav-item">
            <%= link_to "Sign in", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>

      
      
    </div>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Biblios</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">
  </head>

  <body>

    <%= render 'layouts/navbar' %>

    <div class="container">
      <p class="notice"><%= notice %></p>
      <p class="alert"><%= alert %></p>
      <%= yield %>
    </div>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.11.6/dist/umd/popper.min.js" integrity="sha384-oBqDVmMz9ATKxIep9tiCxS/Z9fNfEXiDAYTujMAeBAsjFuCZSmKbSSUnQlmh/jp3" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/js/bootstrap.min.js" integrity="sha384-mQ93GR66B00ZXjt0YO5KlohRA5SY2XofN4zfuZxLkoj1gXtW8ANNCe9d5Y3eG5eD" crossorigin="anonymous"></script>

  </body>
</html>